apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cs3219
  name: order-service-deployment
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      name: order-service
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: cs3219/order-service:1.0.0
        ports:
        - containerPort: 8080